cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3: #????
      bucket: woosik-bucket
    region: #S3 ??
      static: ap-northeast-2
    stack:
      auto: false
# multipartFile ?? ???? ??
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  h2 ??
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:springminiprojectdb
    username: sa
    password:
